/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fundamentos.ra.gradle.teste;

import fundamentos.ra.gradle.dominio.Usuario;
import org.apache.http.HttpStatus;
import org.junit.Test;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.MatcherAssert.assertThat;

// Usa heranca para pegar o setup
public class TesteUsuario extends TesteBase {

    // criar variaveis estaticas para melhor leitura dos testes
    private static final String LISTA_USUARIOS_ENDPOINT = "/users";
    private static final String CRIAR_USUARIO_ENDPOINT = "/user";
    private static final String MOSTRAR_USUARIO_ENDPOINT = "/users/{userId}";


    @Test
    public void testMostraPaginaEspecifica() {

        given().
                param("page","2").

        // url que quero testar
        when().

                // testa metodo GET
                get(LISTA_USUARIOS_ENDPOINT).

        // validacoes que faco para essa url
        then().
                // valida status code
                statusCode(HttpStatus.SC_OK).

                // valida um campo do json de resposta
                body("page",is(2)).

                // valida se o campo data nao esta vazio
                body("data",is(notNullValue()));

    }

    @Test
    public void testCriarUsuarioComSucesso(){

        // instancio o usuario, para passar os campos do json
        // Usuario usuario = new Usuario("vaneyck","analista de teste","van@gmail.com","rosas");

        // Usando hashmap para passar no json apenas os campos necessarios
        Map<String, String> usuario = new HashMap<>();
        usuario.put("name","vaneyck");
        usuario.put("job","analista de testes");


        // .log.all() mostra como ta indo a requisicao
        given().

                // informa que o conteudo do body eh um json
                //contentType(ContentType.JSON).

                // conteudo do body
                body(usuario).

        when().
                // testa metodo POST
                post(CRIAR_USUARIO_ENDPOINT).

        then().
                statusCode(HttpStatus.SC_CREATED).

                body("name",is("vaneyck"));
    }

    @Test
    public void testTamanhoDosItensMostradosIgualAoPerPage() {

        int paginaEsperada = 2;


        int perPageEsperado = retornaPerPageEsperado(paginaEsperada);

        given().
                param("page",paginaEsperada).

        when().
                get(LISTA_USUARIOS_ENDPOINT).
        then().

                statusCode(HttpStatus.SC_OK).

                // o rest assured transforma o array data em um groovy collection
                body(
                        "page",is(paginaEsperada),
                        "data.size()",is(perPageEsperado),
                        // pega cada item do data e checa se o campo avatar comeca com o site da amazon
                        "data.findAll { it.avatar.startsWith('https://s3.amazonaws.com') }.size()", is(perPageEsperado)
                );


    }


    @Test
    public void testMostraUsuarioEspecifico(){

        Usuario usuario = given().
                // criada para passar o id do usuario
                pathParam("userId",2).
        when().
                get(MOSTRAR_USUARIO_ENDPOINT).
        then().
                statusCode(HttpStatus.SC_OK).

        // na resposta do get, pega o campo data, e passa como parametro a classe na qual tem os atributos
        // que permitem fazer as validacoes
        extract().
                body().jsonPath().getObject("data",Usuario.class);

        // realizand as assertivas
        assertThat(usuario.getEmail(), containsString("@reqres.in"));
        assertThat(usuario.getName(), is("Janet"));
        assertThat(usuario.getLastname(), is("Weaver"));

    }



    // guardando uma informacao que vem na resposta de uma requisicao
    private int retornaPerPageEsperado(int page) {
        return given().
                param("page",page).
              when().
                get(LISTA_USUARIOS_ENDPOINT).
              then().
              // faz de novo a requisicao pra checar se realmente bateu no endpoint
                statusCode(HttpStatus.SC_OK).
              // extrai o valor do campo per_page e atribui a variavel
              extract().
                path("per_page");
    }

}
