/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fundamentos.ra.gradle.teste;

import fundamentos.ra.gradle.dominio.Usuario;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

public class UsuarioTeste {


    @BeforeClass
    public static void setUp(){

        // quando o teste falha, habilita os logs da requisicao
        // permitndo mostra como a requisicao foi feita
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();

        // configura para todos os testes o endpoint
        baseURI = "https://reqres.in";
        // configura o path para todos os testes
        basePath = "/api";
    }

    @Test
    public void testListMetaDadosUsuario() {

        given().
                params("page","2").

        // url que quero testar
        when().

                // testa metodo GET
                get("/users").

        // validacoes que faco para essa url
        then().
                // valida status code
                statusCode(HttpStatus.SC_OK).

                // valida um campo do json de resposta
                body("page",is(2)).

                // valida se o campo data nao esta vazio
                body("data",is(notNullValue()));

    }

    @Test
    public void testCriarUsuarioComSucesso(){

        // instancio o usuario, para passar os campos do json
        Usuario usuario = new Usuario("vaneyck","analista de teste");


        // .log.all() mostra como ta indo a requisicao
        given().

                // informa que o conteudo do body eh um json
                contentType(ContentType.JSON).

                // conteudo do body
                body(usuario).

        when().
                // testa metodo POST
                post("/user").

        then().
                statusCode(HttpStatus.SC_CREATED).

                body("name",is("vaneyck"));
    }

}
